name = "MerryMagic&Create"
author = "MrPotato82"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a0583a07e67143a6f3e395c885f84975ddc1d2022813609fc0eeddc4c63a94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.1"]
